#!/usr/bin/python
from subprocess import call
import sys

if len(sys.argv) == 1:
	print "ERROR!! env is missing"
	exit(1)

env = sys.argv[1]
retcode = call(["python", "wswitch", "-e", env])
if retcode != 0:
	exit(1)
call(["./waf", "configure", "build"])
call(["rm", "wscript"])
